node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry([ credentialsId:6a4499da-23ac-4e27-8268-fe24e9b41b1a,'https://index.docker.io/v1/', 'dockerhub']) {
       def app = docker.build("nicholasgull/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
